Models/Competencia.cs
namespace WebAppBloom.Models;
public class Competencia{    
    public int Id { get; set; }
    
    public string? ColunaBloom { get; set; }

    public string? LinhaBloom { get; set; }
    
    public Competencia(){
        
    }
    public Competencia(string? colunaBloom, string? linhaBloom)
    {        
        ColunaBloom = colunaBloom;
        LinhaBloom = linhaBloom;
    }
}

ViewModels/CriarCompetenciaViewModel.cs
namespace WebAppBloom.ViewModels;
public class CriarCompetenciaViewModel{    
       
    public string? ColunaBloom { get; set; }

    public string? LinhaBloom { get; set; }
}

ViewModels/DetalhesCompViewModel.cs
using WebAppBloom.Models;
namespace WebAppBloom.ViewModels;

public class  DetalhesCompViewModel{   
     
     public Competencia? Competencia { get; set; }
     public string TituloPagina { get; set; } = string.Empty;

}

ViewModels/ListaCompetenciaViewModel.cs
using WebAppBloom.Models;
public class ListaCompetenciaViewModel{

    /* Listar */
    /* Jardim de Infância:  
       A E I O U
       Collections
       A B C D E F G H
       Frutas
       Verduras
       Cores
       Figuras

       SBT  GLOBO BAND 
    */

    public ICollection<Competencia> Competencias { get; set; } 
               = new List<Competencia>();

             

}

Controllers/CompetenciaController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppBloom.Models;
using WebAppBloom.ViewModels;
using WebAppBloom.Contexts;
namespace WebAppBloom.Controllers;
public class CompetenciaController : Controller
{

    private readonly AppDbContext _context;

    public CompetenciaController(AppDbContext context)
    {
        _context = context;
    }
    public IActionResult Index()
    {

        Competencia competencia = new Competencia();
        competencia.ColunaBloom = "Memorizar";
        competencia.LinhaBloom = "Listar";
        ViewData["titulo"] = "Compreender o funcionamento do Razor";
        ViewData["tablebloom"] = competencia;
        return View();
    }

    public IActionResult RelatorioCompe()
    {

        var competencias = _context.Competencias.ToList();
        return View();
    }
    public IActionResult Listar()
    {
        //pega os dados do banco
        var listaCompe = _context.Competencias.ToList();

        //envia o objeto listaCompe (dados do banco)
        //para a ViewModel (ICollection<>   List<>)
        var listaViewModel = new ListaCompetenciaViewModel
        {
            Competencias = listaCompe
        };
        return View(listaViewModel);
    }
    public IActionResult Taxonomia(){
         //pega os dados do banco
        var listaCompe = _context.Competencias.ToList();

        //envia o objeto listaCompe (dados do banco)
        //para a ViewModel (ICollection<>   List<>)
        var listaViewModel = new ListaCompetenciaViewModel
        {
            Competencias = listaCompe
        };
        return View(listaViewModel);
        return View();
    }


    public IActionResult Criar()
    {
        ViewData["Titulo"] = "Cadastrar Taxonomia de Bloom";
        return View();
    }
    [HttpPost]
    public IActionResult Criar(CriarCompetenciaViewModel dados)
    {
        var competencia = new Competencia(dados.ColunaBloom, dados.LinhaBloom);
        _context.Add(competencia);
        _context.SaveChanges();
        //Quero redirecionar para a página Listar.cshtml
        return RedirectToAction(nameof(Listar));

    }
    
    public IActionResult Deletar(int id)
    {

        var competencia = _context.Competencias.Find(id);
        if (competencia is null)
        {
            return NotFound();
        }

        _context.Remove(competencia);
        _context.SaveChanges();
        return RedirectToAction(nameof(Listar));

    }


}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebAppBloom.Controllers;
public class HomeController:Controller{
    public IActionResult Index(){
        return View();
    }
}

Views/Competencia/Criar.cshtml
<!--Vamos tipar a View-->

@model CriarCompetenciaViewModel

<!-- Inicio da Div -->
<div class="text-center">

    <!-- Definindo um título H1 os dados estão vindo do ViewData[ ]-->
    <!-- ViewData[] é uma classe que transporta dados do Controller para a View-->
    <h1 class="display-4">@ViewData["titulo"]</h1>
    <!--Inicio do Form-->
    <form method="post">
        <!--Definindo um input text - é uma entrada de dados do tipo text-->     
        <label for="colunas" asp-for="ColunaBloom">Escolha uma Coluna Bloom:</label>
        <input type="text" asp-for="ColunaBloom" id="ColunaBloom" name="ColunaBloom" list="opcoes-colunas">
        <datalist id="opcoes-colunas">
            <option value="Memorizar"></option>
            <option value="Compreender"> </option>
            <option value="Aplicar"></option>
            <option value="Analisar"></option>
            <option value="Avaliar"></option>
            <option value="Criar"></option>
        </datalist>
        <label asp-for="LinhaBloom">Digite a linha Bloom</label>
        <input asp-for="LinhaBloom" type="text">
        <button type="submit">Cadastrar</button>
    </form>
</div>

Views/Competencia/Index.cshtml
Alunos do SENAI - Desenvolvedor DotNet <br>
Cordialmente criaram esse software contribuindo com a educação brasileira













  

Views/Competencia/Listar.cshtml
@model ListaCompetenciaViewModel
<h1>Listando Competências</h1>
<table>   
     <tr>
        <th>Id</th>
        <th>Coluna Bloom</th>
        <th>Linha Bloom</th> 
        <th>Apagar</th>  
     </tr>
     @{
       foreach(var item in Model.Competencias)
       {
          <tr>
              <td>@item.Id</td>
              <td>@item.ColunaBloom</td>
              <td>@item.LinhaBloom</td>
              <td><a href="/Competencia/Deletar/@item.Id">Deletar</a></td>
          </tr>

       } 
     }
</table>

Views/Competencia/RelatorioCompe.cshtml
@model DetalhesCompViewModel;


<h1>@Model.TituloPagina</h1>

Views/Competencia/Taxonomia.cshtml
@model ListaCompetenciaViewModel
<h1>Listando Competências</h1>

<table class="table">
  <thead>
    <tr>
      @{
        Dictionary<string, List<string>> competencias = new Dictionary<string, List<string>>()
        {
            {"MEMORIZAR", new List<string>()},
            {"COMPREENDER", new List<string>()},
            {"APLICAR", new List<string>()},
            {"ANALISAR", new List<string>()},
            {"AVALIAR", new List<string>()},
            {"CRIAR", new List<string>()},
        };

        foreach(var item in Model.Competencias)
        {
            foreach(string key in competencias.Keys)
            {
                if(@item.ColunaBloom?.ToString().ToUpper() == key){competencias[key].Add(@item.LinhaBloom);}
            }
        }
        foreach (string key in competencias.Keys){
            <th scope="col">@key</th>
        };
      }
    </tr>
  </thead>
  <tbody>
    <tbody>
        @{
            for (int i = 0; i < competencias.Values.Count; i++)
            {
                <tr>
                @foreach(string key in competencias.Keys)
                {
                    try{
                        <td>@competencias[key][i]</td>
                    }
                    catch{}
                }
                </tr>
            }
        }
  </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<p>Nosso projeto atende uma demanda dos professores que educam por competência. Aplicando as técnicas de Bloom.</p>

<img src="~/imagens/taxonomia.webp">

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppBloom </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/webappbloom.styles.css" asp-append-version="true" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppBloom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Competencia" asp-action="Index">Competência</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Competencia" asp-action="Criar">Criar</a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Competencia" asp-action="Listar">Manutenção</a>
                        </li>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Competencia" asp-action="Taxonomia">Taxonomia</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AppBloom - QUA.315.030 - Desenvolvedor C# 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>